sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t $DOCKER_USERNAME/shopware-plugin-testing:5.2 .
      - docker images
      - docker push $DOCKER_USERNAME/shopware-plugin-testing:5.2


